model:
    name: "unet"
    in_channels: 3
    n_channels: [32, 64, 128, 256, 512]
    out_channels: 3
    latent_size: 64
    hidden_size: 512
    attn_head_size: 64
    max_timesteps: 1000
    ff_mult_factor: 4
    eps: 1.0e-5

diffusion:
    total_steps: 1000
    beta_min: 0.00001
    beta_max: 0.02
    step_interval: 10

optimizer:
    lr: 1.0e-4
    weight_decay: 1.0e-5
    betas: [0.9, 0.96]

scheduler:
    lr_decay: 0.99999
    warmup_steps: 0
dataset:
    name: laion2B
    root: data/laion2B-en-data
    image_size: 256

dataloader:
    batch_size: 128
    num_workers: 16
    shuffle: true

train:
    total_epochs: 100
    save_every: 100
    swa_start: 1000
    swa_anneal_steps: 10000
    log_dir: logs/laion2B
    max_kl_weight: 1
    min_kl_weight: 0.01
    kl_annealing_steps: 10000
    accumulate_grad_every: 1
